platform :ios, '9.0'
use_frameworks!

target 'tramcloud' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'HandyJSON','4.0.0-beta.1'
    pod 'Moya/RxSwift'
    pod 'RxDataSources'
    pod 'NSObject+Rx'
    pod 'SwifterSwift'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Kingfisher'
    pod 'SwiftyBeaver'
    pod 'Then'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'R.swift'
    pod 'Charts'
    pod 'MJRefresh'
    pod 'CFNotify'
    pod 'Closures'
    pod 'SnapKit'
    pod 'AttributedLib'
    pod 'KSPhotoBrowser'
end
